name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Restore dependencies
      run: dotnet restore
    - name: Install DotCover
      run: dotnet tool install JetBrains.dotCover.GlobalTool -g
    - name: Build ChargeBook
      run: dotnet build ChargeBook/ChargeBook.csproj --no-restore
    - name: Build UnitTests
      run: dotnet build UnitTests/UnitTests.csproj --no-restore
    - name: Test
      run: dotnet dotcover test --no-build --verbosity normal
