name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Restore dependencies
      run: dotnet restore
    - name: Install DotCover
      run: dotnet tool install JetBrains.dotCover.GlobalTool -g
    - name: Build Project
      run: dotnet build ChargeBook/ChargeBook.csproj --no-restore
    - name: Build UnitTests
      run: dotnet build UnitTests/UnitTests.csproj --no-restore
    - name: TestCoverage
      run: dotnet dotcover test UnitTests/UnitTests.csproj --no-build --verbosity normal --dcReportType=DetailedXML --dcOutput="/home/runner/work/code_cov_seminar/code_cov_seminar/Coverage.xml"
    - name: Save Coverage Report in Artifact
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage-report
        path: Coverage.xml
      if: ${{ always() }}
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        directory: /home/runner/work/code_cov_seminar/code_cov_seminar/
        fail_ci_if_error: true
        files: ./Coverage.xml
        flags: unittests
        name: codecov-DotCover
        path_to_write_report: ./codecov_report.txt
        verbose: true
                